In [14]:
import pandas as pd

df = pd.read_csv('../data/rallit.csv')
df = df.dropna(subset=['직업'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 826 entries, 0 to 867
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   직업      826 non-null    object
 1   기술 스택   720 non-null    object
 2   경력      544 non-null    object
 3   프로젝트    582 non-null    object
 4   대외활동    271 non-null    object
 5   교육      536 non-null    object
 6   자격증     289 non-null    object
 7   외국어     113 non-null    object
dtypes: object(8)
memory usage: 58.1+ KB

In [15]:
df.head()

,직업,기술 스택,경력,프로젝트,대외활동,교육,자격증,외국어
0,FrontEnd Engineer,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,프론트엔드 개발자,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"끝없는 도전, 끝없는 성과 - 서비스백엔드 주니어 개발자 이재혁","Python, Java, C, Django, Spring Boot, FastAPI,...","SLBM 연구실, 학부연구생 | SLBM 연구실 | 재직 중, 2022.10. ~ ...","정신건강 모니터링 플랫폼 운영 및 유지보수, SLBM 연구실, 2022.12. ~ ...","국외 단기현장 실습, SW사업단 - Okta Singapore, , '22년 6월 ...","강원대학교, 대학교(학사) | 컴퓨터 정보통신공학 전공, 2018.03. ~ 현재 ...","정보처리기사, 한국산업인력공단, 2023.11., 2종보통운전면허, 경찰청(운전면허...","영어, 일상 회화 가능"
3,프론트엔드 개발자,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,프론트앤드 개발자,"JavaScript, TypeScript, React, Python, IPFS",NaN,"Selly, 삼성청년소프트웨어 아카데미, 2022.10. ~ 2022.11., gi...",NaN,"삼성청년소프트웨어 아카데미, 사설 교육 | python 반, 2022.01. ~ 2...",NaN,NaN

In [18]:
df = df.dropna(subset=df.columns.difference(['직업']), how='all')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 756 entries, 2 to 867
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   직업      756 non-null    object
 1   기술 스택   720 non-null    object
 2   경력      544 non-null    object
 3   프로젝트    582 non-null    object
 4   대외활동    271 non-null    object
 5   교육      536 non-null    object
 6   자격증     289 non-null    object
 7   외국어     113 non-null    object
dtypes: object(8)
memory usage: 53.2+ KB

In [19]:
df['직업'].value_counts()

직업
백엔드 개발자                                 234
프론트엔드 개발자                               201
풀스택 개발자                                  10
웹 프론트엔드 개발자                               9
소프트웨어 엔지니어                                7
                                       ...
프로덕트 매니저                                  1
FE 소프트웨어 엔지니어                             1
SDK 개발자                                   1
Web Server Developer, Problem Solver      1
데이터+백엔드 엔지니어                              1
Name: count, Length: 208, dtype: int64

In [20]:
import numpy as np

# 조건에 따라 각 직업 유형 정의
conditions = [
    df['직업'].str.contains('풀|Full|full|웹|앱|Web|App|Software|소프트웨어', na=False),
    df['직업'].str.contains('데이터 엔지니어|Data Engineer|data engineer', na=False),
    df['직업'].str.contains('백|벡|Back|back|Node.js|서버|Server|java|Java|spring|Spring|Cloud|Reliability', na=False),
    df['직업'].str.contains('데이터|Data|data|AI|머신러닝', na=False),
    df['직업'].str.contains('데브옵스|Devops|DevOps|devops', na=False),
    df['직업'].str.contains('PM|기획|서비스|Product', na=False),
    df['직업'].str.contains('프론트|프런트|Front|front|React|react|Android|안드로이드|iOS|ios|플러터|PHP', na=False),
    df['직업'].str.contains('Sales|영업|마케터', na=False)
]

# 각 직업 유형에 해당하는 값 정의
values = [
    '풀스택 개발자',
    '데이터 엔지니어',
    '백엔드 개발자',
    '데이터 분석가',
    '데브옵스 엔지니어',
    'PM',
    '프론트엔드 개발자',
    'Sales'
]

# 조건에 따라 새로운 열에 해당하는 값을 할당
df['직무'] = np.select(conditions, values, default='기타')

df

,직업,기술 스택,경력,프로젝트,대외활동,교육,자격증,외국어,직무
2,"끝없는 도전, 끝없는 성과 - 서비스백엔드 주니어 개발자 이재혁","Python, Java, C, Django, Spring Boot, FastAPI,...","SLBM 연구실, 학부연구생 | SLBM 연구실 | 재직 중, 2022.10. ~ ...","정신건강 모니터링 플랫폼 운영 및 유지보수, SLBM 연구실, 2022.12. ~ ...","국외 단기현장 실습, SW사업단 - Okta Singapore, , '22년 6월 ...","강원대학교, 대학교(학사) | 컴퓨터 정보통신공학 전공, 2018.03. ~ 현재 ...","정보처리기사, 한국산업인력공단, 2023.11., 2종보통운전면허, 경찰청(운전면허...","영어, 일상 회화 가능",백엔드 개발자
4,프론트앤드 개발자,"JavaScript, TypeScript, React, Python, IPFS",NaN,"Selly, 삼성청년소프트웨어 아카데미, 2022.10. ~ 2022.11., gi...",NaN,"삼성청년소프트웨어 아카데미, 사설 교육 | python 반, 2022.01. ~ 2...",NaN,NaN,프론트엔드 개발자
5,인프런 / 쿠버네티스 / 지식공유자,"Kubernetes, Prometheus, Docker, helm, nginx, J...","한화시스템 (프리랜서), 아키텍트 | 인프라팀 | 퇴사, 2020.05. ~ 202...","흥국생명 차세대 프로젝트, 한화시스템, 2022.10. ~ 2023.04., ?? ...","???♂? 마라톤, MJ클럽, , 경력 7년 (풀 코스 4회, 하프 코스 5회, 1...","?? 가천대학교 (수석졸업??/253명), 대학교(학사) | IT학부, 2003.0...","? NAVER CLOUD PLATFORM Certified Professional,...",NaN,기타
6,서버 개발자,Java\r\nSpring Boot\r\nJPA\r\nTypeScript\r\nAW...,"인프랩, CTO ? 개발팀, 제품 조직과 시스템의 성장이 비즈니스의 성과가 될 수 ...","인프랩, 랠릿 서비스 런칭, 신규 채용 서비스 랠릿 오픈 프로젝트\r\n프로젝트 전...",NaN,"비트교육 센터, 사설 교육 | 웹개발 고급 과정, 2011.10. ~ 2012.02...",NaN,NaN,백엔드 개발자
7,Back-End Engineer,Java\r\nKotlin\r\nJavaScript\r\nTypeScript\r\n...,"디어코퍼레이션, 디어관제팀, 디어코퍼레이션은 공유 킥보드 서비스를 제공하는 스타트업...","디어코퍼레이션, Vehicle System, Vehicle System은 전반적으로...","글또, 글또 9기, , 2023, AUSG, AUSG 7기, , 2023, AWS,...","중앙대학교, 대학교(학사) | 전자전기공학부 / 소프트웨어학부(복수전공) | 이수 ...","AWS Certified Solutions Architect Associate, A...",NaN,백엔드 개발자
...,...,...,...,...,...,...,...,...,...
862,Android 개발자,"Android, Kotlin",NaN,NaN,NaN,NaN,NaN,NaN,프론트엔드 개발자
864,백엔드 개발자,"Java, JSP, servlet, Spring, Oracle, Git",NaN,NaN,NaN,NaN,NaN,NaN,백엔드 개발자
865,데이터+백엔드 엔지니어,NaN,"알체라DS, 재직 중, 2024.01. ~ 재직 중 (4개월), 파이썬 스크립터로서...",NaN,NaN,NaN,NaN,NaN,백엔드 개발자
866,iOS Developer,"Swift, SwiftUI, RxSwift, MVVM, MVC, Oracle, Gi...","코나아이(주), 사원 | 앱개발팀 | 재직 중, 2022.01. ~ 재직 중 (2년...","AML 솔루션 - EDD 프로세스 개발, 코나아이, 2022.06. ~ 2023.0...",NaN,"한성대학교, 대학교(학사) | 컴퓨터공학, 2016.03. ~ 2022.02. | 졸업",NaN,NaN,프론트엔드 개발자
867,Frontend Developer,"JavaScript, React, HTML/CSS, TypeScript","（주）비바리퍼블리카, 사원 | Frontend Developer Assistant ...","실시간 채팅기능을 탑재한 성수엘리스랩 예약 플랫폼, 개인, 2023.05. ~ 20...",NaN,"한양대학교(분교), 대학교(학사) | 주전공) 경영학부, 제2전공) ICT융합학부,...","정보처리기사, 기사 | 한국산업인력공단, 2022.06., 컴퓨터활용능력, 1급 |...",NaN,프론트엔드 개발자

In [21]:
df[(df['직무'] == '기타') & (~df['직업'].str.contains('학생', na=False))].count()

직업       45
기술 스택    42
경력       35
프로젝트     25
대외활동     19
교육       30
자격증      16
외국어       7
직무       45
dtype: int64

In [22]:
df = df[(df['직무'] != '기타') & (~df['직무'].isna())]

In [23]:
df.groupby('직무')['기술 스택'].count()

직무
PM            19
Sales          6
데브옵스 엔지니어      7
데이터 분석가       12
데이터 엔지니어       6
백엔드 개발자      309
풀스택 개발자       69
프론트엔드 개발자    244
Name: 기술 스택, dtype: int64

In [24]:
df[(df['직무'] == '데이터 분석가')]

,직업,기술 스택,경력,프로젝트,대외활동,교육,자격증,외국어,직무
128,데이터사이언티스트,"Python, bigquery, SQL, SQLD, Tableau, looker-s...","(주)골든플래닛, 파트장(시니어 매니저) | DX엔지니어링 데이터분석 유닛 | 재직...","프랜차이즈 지리정보 기반 상권 분석 플랫폼 구축, 골든플래닛, 2023.04. ~ ...",NaN,"성균관대학교 일반대학원, 대학원(석사) | 인지심리, 2016.03. ~ 2019....","GA4 데이터 분석 캠프 수료증, 수료 | 데이터리안, 2024.04., SQL 개...",NaN,데이터 분석가
269,ex-OpenAI,"PyTorch, Tensorflow, Python, JavaScript","SHIFT UP, Head of AI | AI Labs | 재직 중, 2023.05...",NaN,NaN,NaN,NaN,NaN,데이터 분석가
279,"데이터 사이언티스트, 머신러닝 엔지니어","Python, MQTT, Kafka, grafana, Prometheus, C#, ...","주식회사 반프, 매니저 | R&D | 퇴사, 2022.11. ~ 2023.09. (...",NaN,NaN,"공주대학교, 대학원(석사) | 컴퓨터공학과, 2019.03. ~ 2021.02. |...","AWS CLF-01, Amazon Web Service, 2023.05.",NaN,데이터 분석가
386,데이터 마케팅,"Python, Excel, Google Analytics, Facebook Ads,...","(주)YG엔터테인먼트, 데이터마케팅 | IT지원그룹 데이터사이언스팀 | 재직 중, ...",K-POP Fandom Data Report (Quarterly / Monthly ...,"Galaxy S10 Supporters, SAMSUNG (삼성전자), , , HAP...","동아대학교, 대학교(학사) | 경영학과, 2016.02. ~ 2022.02. | 졸업","Big Data Expert Level-2 (빅데이터전문가 2급), KMAC 한국능...","영어, 비즈니스 회화 가능",데이터 분석가
388,AI Engineer,"Python, PyTorch, Tensorflow, OpenCV, Pandas, M...","크레스콤, 연구원 | 기업부설연구소 | 재직 중, 2022.03. ~ 재직 중 (2...",NaN,NaN,NaN,NaN,NaN,데이터 분석가
536,데이터 분석가,"SQL, Python, R, Airflow, Apache Spark, Tableau","넥슨코리아, 사원 | 분석지원팀 | 재직 중, 2020.12. ~ 재직 중 (3년 ...",NaN,NaN,"건국대학교, 대학교(학사) | 응용통계학, 2013.03. ~ 2019.02. | ...",NaN,NaN,데이터 분석가
537,데이터 분석가,"Python, MySQL, Tableau, MS-Office, GitHub, Goo...",NaN,"천안시 데이터기반 시각화 아이디어 공모전 3위, 한국평가데이터, 2022.09. ~...","빅데이터 기반 비즈니스 분석가 3개월 양성 과정, 한국직업개발원, , 공공데이터를 ...","계명대학교, 대학교(학사) | 광고홍보학전공, 2020.03. ~ 2024.03. ...","데이터분석준전문가(ADsP), 합격 | 한국데이터베이스진흥원, 2023.11.",NaN,데이터 분석가
637,머신러닝 개발자,"PyTorch, 머신러닝, Python, MATLAB, mathematics",NaN,NaN,NaN,"성균관대학교, 대학원(박사) | 수학과, 2023.02. ~ 현재 | 재학 중",NaN,NaN,데이터 분석가
665,데이터에 기반하여 어려운 문제를 해결하는 개발자,"React, Next.js, Node.js, JavaScript, TypeScrip...","오웰헬스, Frontend Engineer | 제품 개발팀 | 퇴사, 2021.12...","정신건강 관리 React Webview 개발, 오웰헬스, 2022.05. ~ 202...",NaN,NaN,NaN,NaN,데이터 분석가
763,데이터 분석가,"Python, MySQL, Tableau, MS-Office, GitHub, Goo...",NaN,"세 줄 독후감, 개인 프로젝트, 2023.01. ~ 2023.06., [개발자와 협...","빅데이터 기반 비즈니스 분석가 3개월 양성 과정, 한국직업개발원, , 공공데이터를 ...","계명대학교, 대학교(학사) | 광고홍보학전공, 2020.03. ~ 2024.02. ...","데이터분석준전문가(ADsP), 합격 | 한국데이터베이스진흥원, 2023.11.",NaN,데이터 분석가
838,Data Analyst,"Python, Tensorflow, PyTorch, R, Photoshop, Ill...","Flex Math, 보조강사 | 교육팀 | 퇴사, 2019.02. ~ 2023.11...",NaN,"통계 교육 재능기부단 (교육 봉사), 통계교육원, 한국통계진흥원, , , 태블로 신...","숭실대학교, 대학교(학사) | 수학과 (복수전공: 정보통계보험수리학과) / 학점 :...","SQL, 개발자 (SQLD) | 한국데이터산업진흥원, 2023.12., 데이터분석,...",NaN,데이터 분석가
839,Data Analyst,"Python, Tensorflow, PyTorch, R, Photoshop, Ill...","Flex Math, 보조강사 | 교육팀 | 퇴사, 2019.02. ~ 2023.11...",NaN,"통계 교육 재능기부단 (교육 봉사), 통계교육원, 한국통계진흥원, , , 태블로 신...","숭실대학교, 대학교(학사) | 수학과 (복수전공: 정보통계보험수리학과) / 학점 :...","SQL, 개발자 (SQLD) | 한국데이터산업진흥원, 2023.12., 데이터분석,...",NaN,데이터 분석가

In [25]:
def combine_columns(row):
    info_parts = []
    columns = ['기술 스택', '경력', '프로젝트', '대외활동', '교육', '자격증', '외국어']
    for col in columns:
        if pd.notna(row[col]):
            info_parts.append(f"{col}: {row[col]}")
    return ", ".join(info_parts)

df['text'] = df.apply(combine_columns, axis=1)
df

C:\Users\DESKTOP\AppData\Local\Temp\ipykernel_6580\3032308294.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text'] = df.apply(combine_columns, axis=1)

,직업,기술 스택,경력,프로젝트,대외활동,교육,자격증,외국어,직무,text
2,"끝없는 도전, 끝없는 성과 - 서비스백엔드 주니어 개발자 이재혁","Python, Java, C, Django, Spring Boot, FastAPI,...","SLBM 연구실, 학부연구생 | SLBM 연구실 | 재직 중, 2022.10. ~ ...","정신건강 모니터링 플랫폼 운영 및 유지보수, SLBM 연구실, 2022.12. ~ ...","국외 단기현장 실습, SW사업단 - Okta Singapore, , '22년 6월 ...","강원대학교, 대학교(학사) | 컴퓨터 정보통신공학 전공, 2018.03. ~ 현재 ...","정보처리기사, 한국산업인력공단, 2023.11., 2종보통운전면허, 경찰청(운전면허...","영어, 일상 회화 가능",백엔드 개발자,"기술 스택: Python, Java, C, Django, Spring Boot, F..."
4,프론트앤드 개발자,"JavaScript, TypeScript, React, Python, IPFS",NaN,"Selly, 삼성청년소프트웨어 아카데미, 2022.10. ~ 2022.11., gi...",NaN,"삼성청년소프트웨어 아카데미, 사설 교육 | python 반, 2022.01. ~ 2...",NaN,NaN,프론트엔드 개발자,"기술 스택: JavaScript, TypeScript, React, Python, ..."
6,서버 개발자,Java\r\nSpring Boot\r\nJPA\r\nTypeScript\r\nAW...,"인프랩, CTO ? 개발팀, 제품 조직과 시스템의 성장이 비즈니스의 성과가 될 수 ...","인프랩, 랠릿 서비스 런칭, 신규 채용 서비스 랠릿 오픈 프로젝트\r\n프로젝트 전...",NaN,"비트교육 센터, 사설 교육 | 웹개발 고급 과정, 2011.10. ~ 2012.02...",NaN,NaN,백엔드 개발자,기술 스택: Java\r\nSpring Boot\r\nJPA\r\nTypeScrip...
7,Back-End Engineer,Java\r\nKotlin\r\nJavaScript\r\nTypeScript\r\n...,"디어코퍼레이션, 디어관제팀, 디어코퍼레이션은 공유 킥보드 서비스를 제공하는 스타트업...","디어코퍼레이션, Vehicle System, Vehicle System은 전반적으로...","글또, 글또 9기, , 2023, AUSG, AUSG 7기, , 2023, AWS,...","중앙대학교, 대학교(학사) | 전자전기공학부 / 소프트웨어학부(복수전공) | 이수 ...","AWS Certified Solutions Architect Associate, A...",NaN,백엔드 개발자,기술 스택: Java\r\nKotlin\r\nJavaScript\r\nTypeScr...
8,풀스택 개발자,"JavaScript, Docker, Elasticsearch, Vue.js, Rea...","토피도, 대리 | DSU | 퇴사, 2018.06. ~ 2023.04. (4년 11...","도로공사 데이터 안심구역을 위한 연계,수집,저장 플랫폼 개발, 토피도, 2022.0...",NaN,"한국정보기술연구원, 사설 교육 | 공공 데이터 기반 java application ...","정보처리기사, 한국산업인력공단, 2015.05.",NaN,풀스택 개발자,"기술 스택: JavaScript, Docker, Elasticsearch, Vue...."
...,...,...,...,...,...,...,...,...,...,...
862,Android 개발자,"Android, Kotlin",NaN,NaN,NaN,NaN,NaN,NaN,프론트엔드 개발자,"기술 스택: Android, Kotlin"
864,백엔드 개발자,"Java, JSP, servlet, Spring, Oracle, Git",NaN,NaN,NaN,NaN,NaN,NaN,백엔드 개발자,"기술 스택: Java, JSP, servlet, Spring, Oracle, Git"
865,데이터+백엔드 엔지니어,NaN,"알체라DS, 재직 중, 2024.01. ~ 재직 중 (4개월), 파이썬 스크립터로서...",NaN,NaN,NaN,NaN,NaN,백엔드 개발자,"경력: 알체라DS, 재직 중, 2024.01. ~ 재직 중 (4개월), 파이썬 스크..."
866,iOS Developer,"Swift, SwiftUI, RxSwift, MVVM, MVC, Oracle, Gi...","코나아이(주), 사원 | 앱개발팀 | 재직 중, 2022.01. ~ 재직 중 (2년...","AML 솔루션 - EDD 프로세스 개발, 코나아이, 2022.06. ~ 2023.0...",NaN,"한성대학교, 대학교(학사) | 컴퓨터공학, 2016.03. ~ 2022.02. | 졸업",NaN,NaN,프론트엔드 개발자,"기술 스택: Swift, SwiftUI, RxSwift, MVVM, MVC, Ora..."
867,Frontend Developer,"JavaScript, React, HTML/CSS, TypeScript","（주）비바리퍼블리카, 사원 | Frontend Developer Assistant ...","실시간 채팅기능을 탑재한 성수엘리스랩 예약 플랫폼, 개인, 2023.05. ~ 20...",NaN,"한양대학교(분교), 대학교(학사) | 주전공) 경영학부, 제2전공) ICT융합학부,...","정보처리기사, 기사 | 한국산업인력공단, 2022.06., 컴퓨터활용능력, 1급 |...",NaN,프론트엔드 개발자,"기술 스택: JavaScript, React, HTML/CSS, TypeScript..."

In [26]:
rallit_text = df[['직무', 'text']].copy()
rallit_text.columns = ['job', 'text']
rallit_text.to_csv('../data/rallit_text.csv', index=False)

In [27]:
rallit_text

           job                                               text
2      백엔드 개발자  기술 스택: Python, Java, C, Django, Spring Boot, F...
4    프론트엔드 개발자  기술 스택: JavaScript, TypeScript, React, Python, ...
6      백엔드 개발자  기술 스택: Java\r\nSpring Boot\r\nJPA\r\nTypeScrip...
7      백엔드 개발자  기술 스택: Java\r\nKotlin\r\nJavaScript\r\nTypeScr...
8      풀스택 개발자  기술 스택: JavaScript, Docker, Elasticsearch, Vue....
..         ...                                                ...
862  프론트엔드 개발자                             기술 스택: Android, Kotlin
864    백엔드 개발자     기술 스택: Java, JSP, servlet, Spring, Oracle, Git
865    백엔드 개발자  경력: 알체라DS, 재직 중, 2024.01. ~ 재직 중 (4개월), 파이썬 스크...
866  프론트엔드 개발자  기술 스택: Swift, SwiftUI, RxSwift, MVVM, MVC, Ora...
867  프론트엔드 개발자  기술 스택: JavaScript, React, HTML/CSS, TypeScript...

[705 rows x 2 columns]